### ISSUE TITLE
issue with seagrass and kelp placement

### ISSUE THREAD

**Issue by Mofo50C** [Azmalent/backported-flora#2]
Hi there, so i've been trying to simulate 1.13 using this mod and cofh world but i just can't get the seagrass and kelp to spawn properly. Ive noticed that in game and in the code you can't place the seagrass or kelp unless there is water above them so when i generate them in bodies of water with cofh world, if the plant is the last block before the surface the textures glitch and look like this:
![2020-12-24_22 43 16](https://user-images.githubusercontent.com/21063744/103107771-77af7600-4639-11eb-8dd2-56333d38777a.png)

I know its quite a stretch but  if its not too hard, would it be possible to somehow fix this.

**Comment by Azmalent** [comment]
Hi, sorry for the late reply!
Unfortunately, this is impossible to fix since there is no true waterlogging in 1.12. This is the reason why seagrass and kelp need a block of water above them. If you look at water plants from other mods (i.e. kelp from Biomes O' Plenty), they are implemented similarly.
